import type { Metadata } from "next";
import localFont from "next/font/local";
import { QueryProvider } from "@/shared/api";
import "./globals.css";

const wantedSans = localFont({
  src: "../../../packages/ui/fonts/WantedSansVariable.woff2",
  variable: "--font-wanted-sans",
  display: "swap",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${wantedSans.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
